language: node_js
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
sudo: required
addons:
  apt:
    packages:
      - google-chrome-beta
before_script:
  - yarn
script:
  - yarn run test