dist: xenial
sudo: required
language: node_js
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
addons:
  apt:
    packages:
      - google-chrome-beta
env:
  - CHROME_BIN=/usr/bin/google-chrome-beta
before_script:
  - yarn
script:
  - yarn run test