dist: trusty
sudo: required
language: node_js
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
addons:
   apt:
      sources:
         - google-chrome
      packages:
         - google-chrome-stable
before_script:
  - yarn
script:
  - google-chrome --version
  - yarn run test